name: 'Terraform provider registry'
description: 'Github action to publish terraform provider into github pages'
author: 'Dinar Valeev'
branding:
  icon: 'command'
  color: 'blue'
inputs:
  token:
    description: 'Github Token'
    required: true
  artifacts_dir:
    description: "directory which holds provider artifacts, defaults to `artifacts`"
  repository:
    description: "The GitHub repository to store registry metadata, defaults to `<REPOSITORY>`"
  branch:
    description: "The branch to publish artifacts, defaults to `gh-pages`"
    required: false
  commit_username:
    description: "The user name used for the commit user"
    required: false
    default: ${{ github.actor }} 
  commit_email:
    description: "The email used for the commit user"
    required: false
    default: ${{ github.actor }}@users.noreply.github.com
  target_dir:
    description: "Directory where to push artifacts and metadata into, defaults to `.`"
  namespace:
    description: "Terraform provider namespace, defaults to <REPOSITORY>"
  gpg_keyid:
    description: "Key id used to sign provider"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.token }}
    - ${{ inputs.artifacts_dir }}
    - ${{ inputs.repository}}
    - ${{ inputs.branch }}
    - ${{ inputs.commit_username }}
    - ${{ inputs.commit_email }}
    - ${{ inputs.target_dir }}
    - ${{ inputs.namespace }}
    - ${{ inputs.gpg_keyid }}
